### ISSUE TITLE
16.23 Broken "intermediate product" detection for modules

### ISSUE THREAD

**Issue by marioandrest** [Helfima/helmod#122]
Update 16.23 seems to have broken my Helmod Mod - for some reason it doesn't think "iron gear wheel" and others are a recipe that are intermediate products and hence doesn't allow me to plan for them to have productivity modules.

![helmodbug](https://user-images.githubusercontent.com/61785/36095863-c3e0dd90-0fa8-11e8-8f14-887e146d4c4a.PNG)

**Comment by Helfima** [comment]
oh i mean that something changed

from factorio forum: Fixed Lua module limitations array being a map of strings to numbers, instead of an array.

https://forums.factorio.com/viewtopic.php?f=3&t=57752

you can unlock for all item in Mod settings/Module restrictions in factories
![image](https://user-images.githubusercontent.com/20326713/36097262-87a995a4-0ffa-11e8-89ec-a19e62fbc8bf.png)

**Comment by Helfima** [comment]
fixed v0.7.7
