### ISSUE TITLE
Error with Angels Bioprocessing

### ISSUE THREAD

**Issue by TheBreadbird** [Helfima/helmod#124]
I am not quite sure why its happening but when I try to calculate seed production in your mod I get this error in chat: 
[https://i.imgur.com/Bvfyttm.jpg](https://i.imgur.com/Bvfyttm.jpg)
[https://i.imgur.com/RR3Ytes.jpg](https://i.imgur.com/RR3Ytes.jpg)
[https://i.imgur.com/rPMyFOl.jpg](https://i.imgur.com/rPMyFOl.jpg) 
Its not the end of the world since its easy to calculate but I just wanted you to be aware of this happening if it hasn't been mentioned before.

**Comment by mrvn** [comment]
In 0.16 angels bioprocessing has recipes that output e.g. 1 desert-garden and 5% desert-garden. The product desert-garden appears twice. This causes an exception in helmod because the gui element desert-garden already exists for the products.

Helmod does not handle recipes with the same product appearing multiple times. I think that is the same problem as the above screenshots.
