### ISSUE TITLE
Group recipe execution run slowly

### ISSUE THREAD

**Issue by Helfima** [Helfima/helmod#170]
I do not know what the implications would be, but would it be a solution not to load disabled recipes by default? Mid-game with Angel's and Bob's this reduces the load time drastically on my save.

The current method:
```lua 
function RecipeSelector.methods:updateGroups(item, item2, item3)
Logging:trace(self:classname(), "updateGroups():", item, item2, item3)
  local global_player = Player.getGlobal()
  local global_gui = Player.getGlobalGui()
  -- recuperation recipes
  local list_group = {}
  local list_subgroup = {}
  local list_prototype = {}

  firstGroup = nil
  for key, recipe in pairs(Player.getRecipes()) do
    self:appendGroups(recipe.name, "recipe", list_group, list_subgroup, list_prototype)
  end

...
```

Proposed method:
```lua 
function RecipeSelector.methods:updateGroups(item, item2, item3)
Logging:trace(self:classname(), "updateGroups():", item, item2, item3)
  local global_player = Player.getGlobal()
  local global_gui = Player.getGlobalGui()

  local filter_show_disable = Player.getGlobalSettings("filter_show_disable")
  local filter_show_hidden = Player.getGlobalSettings("filter_show_hidden")

  -- recuperation recipes
  local list_group = {}
  local list_subgroup = {}
  local list_prototype = {}

  firstGroup = nil
  for key, recipe in pairs(Player.getRecipes()) do
    if recipe.enabled == true or filter_show_disable == true then
      self:appendGroups(recipe.name, "recipe", list_group, list_subgroup, list_prototype)
    end
  end

...
```

Another possibilty I see is in the appendGroups method of the selector and that is to move the "load" inside the If statements

```Lua
function RecipeSelector.methods:appendGroups(name, type, list_group, list_subgroup, list_prototype)
  Logging:trace(self:classname(), "appendGroups()", name, type)
  RecipePrototype.load(name, type) -- <<<<<<<<<<<  THIS
  local find = self:checkFilter(RecipePrototype)
  local filter_show_disable = Player.getGlobalSettings("filter_show_disable")
  local filter_show_hidden = Player.getGlobalSettings("filter_show_hidden")

  if
    find == true and (RecipePrototype.getEnabled() == true or filter_show_disable == true) and
      (RecipePrototype.getHidden() == false or filter_show_hidden == true)
   then
    -- <<<<<<<<<<<<<<< TO HERE
    local lua_recipe = RecipePrototype.native()
    local group_name = lua_recipe.group.name
    local subgroup_name = lua_recipe.subgroup.name

    if firstGroup == nil then
      firstGroup = group_name
    end
    list_group[group_name] = lua_recipe.group
    list_subgroup[subgroup_name] = lua_recipe.subgroup
    if list_prototype[group_name] == nil then
      list_prototype[group_name] = {}
    end
    if list_prototype[group_name][subgroup_name] == nil then
      list_prototype[group_name][subgroup_name] = {}
    end
    table.insert(list_prototype[group_name][subgroup_name], {name = name, type = type, order = lua_recipe.order})
  end
end
```

I think moving the entire filter to the updateGroups method might be the better solution, as the appendGroups method should not be called for recipes that are not displayed.

_Originally posted by @Oaquasis in https://github.com/Helfima/helmod/issues/160#issuecomment-473523239_

**Comment by Helfima** [comment]
I Search the best solution
I does changing the runtime of my Mod
now I can run on few ticks
I mean I must change the group generation:

1. run prepare group in a another tick
2. remove choose filter_show_disable and filter_show_hidden in the settings mod

**Comment by Helfima** [comment]
ohh I can move RecipePrototype.load because is using in the checkFilter
RecipePrototype is a proxy to get Lua_RecipePrototype in the game

**Comment by Oaquasis** [comment]
Ah yeah, that is a great idea and not that difficult to implement either!
Moving the prototype loading in the IF statement should boost the performance because it's the Prototype loading that generates the delay, as far as I can see.
I checked the other selectors and you might want to consider doing that on all the other selectors as well.

As for the best solution. I'm not someone with advanced programming skills and I am fairly new to the whole lua and Factorio modding programming. But when I think about what you could do to boost the performance, a couple of options come to mind:

1. Load all the recipes on opening the GUI for the first time, and then cache them somehow. The rest of the mod should then be able to use the cache.
2. Something like "just-in-time"-prototype loading. To build the RecipeSelector, you might not need the entire recipe, but just a couple of things (ingredients, icon, name, localised name). You can then load the entire prototype (if needed) when the player clicks the icon in the recipe selector and go from there. (same for clicking a recipe in the Production block rows).

A drawback of  no. 1  is that it has the same type of "game not responding" problem, but now only when opening the GUI. So it might help with using the mod, but it is still a problem.
The second option should help the most with performance, but might be a lot of code-refactoring.

**Comment by Oaquasis** [comment]
> Moving the prototype loading in the IF statement should boost the performance because it's the Prototype loading that generates the delay, as far as I can see.

After testing, it seems that I this comment doesn't make any sense :) ... I'll try to come up with something else.

**Comment by Helfima** [comment]
I have do a different change in v0.8.7 and now is 50% faster
I run on 2 ticks
the next step need add cache

**Comment by Helfima** [comment]
more faster in v0.8.10
