### ISSUE TITLE
preferenced window is too tall to fit on the screen with too many mods adding things

### ISSUE THREAD

**Issue by LordMZTE** [Helfima/helmod#224]
i have so many items that the preferences window is way too tall to fit onto the screen it would be nice to add a scroll bar to the whole thing

https://i.imgur.com/KiYJKtJ.jpg

factorio version: 0.17.79
helmod version: 0.9.21

**Comment by Helfima** [comment]
hello
you are too items :)
I mean fixed in v0.9.22
and i have added a preference
![image](https://user-images.githubusercontent.com/20326713/72555014-149b5800-389c-11ea-8fa5-150457b2c94f.png)
![image](https://user-images.githubusercontent.com/20326713/72555062-2aa91880-389c-11ea-8959-edeef7c42461.png)

if is it not enough or not well, perhaps need add tab

**Comment by LordMZTE** [comment]
thanks! that should fix my issue!

**Comment by LordMZTE** [comment]
so turns out its still too big even with the amount of columns set to maximum
https://i.imgur.com/KNFKVBR.jpg

**Comment by Helfima** [comment]
actually for you 3 mean the better value, and it's not column but the amount of line
I made a rapid fix, but i can do more

**Comment by LordMZTE** [comment]
oh sorry i misread it. i set it to 1 and the window fits! thanks

**Comment by Helfima** [comment]
I will do a better solution, 1 line is very little

**Comment by Helfima** [comment]
tab added in v0.9.27
