### ISSUE TITLE
fix the power calculation

### ISSUE THREAD

**Issue by Helfima** [Helfima/helmod#241]
I mean there are bad computing, fluid consumption, energy consumption
Need add a unit test

**Comment by matrix47** [comment]
In Py mods, fuel consumption is broken for all miners.
Everything is off by 60 (60 times less consumption).
I think the problem is this line: https://github.com/Helfima/helmod/blob/master/model/ItemPrototype.lua#L23
Why multiply by 60 here?
Same thing in FluidPrototype.lua

But of course not multiplying by this breaks boilers. This is because their speed is 60.
I think the proper fix would be adding the division by factory.speed here:
https://github.com/Helfima/helmod/blob/master/model/RecipePrototype.lua#L358

I managed to fix things for myself locally, but I'm not sure if my fix works for all use cases..

**Comment by Helfima** [comment]
fixed in v0.10.16
