### ISSUE TITLE
Feature: allow few beacon for the same recipe

### ISSUE THREAD

**Issue by Helfima** [Helfima/helmod#287]
by Austin: Hey, sorry if this has been asked before, but I am playing on Krastorio 2 and I am trying out Helmod.  How do I apply 2 kinds of beacons to the same machine? I have setups that use 8 singularity and 11 normal beacons, how do I set helmod to accept that?

**Comment by KiwiHawk** [comment]
Related request from forums: https://mods.factorio.com/mod/helmod/discussion/62b31c1f0d4dcd8e51c90ff6

Currently when planning production, all beacons attached to a structure are forced to have the same Module inventory. Is it possible to let the player select multiple groups of beacons? Here's an example:

I have a building surrounded by 12 beacons, worth 24 slots total. Let's say I want to have 10 Beacons with Productivity modules worth 20 Productivity Modules total and 2 Beacons with Speed modules worth 4 Speed Modules total, regardless of what's in the building itself. Currently, I can't do that. I can have 24 Productivity, 24 Speed or 12/12 Productivity Speed.

![image](https://user-images.githubusercontent.com/59639/175441365-151d9728-b25d-4ac2-a89a-6c81462c2cb2.png)

I use the "productivity in beacons" mod, but hat was just an example. It could very easily be 10 Beacons with Speed Modules and two with Efficiency Modules. Or any other combination of modded modules. My issue right now is that all modules on the same line have to have the exact same inventory, because each line has only a single entry for beacon inventory.

**Comment by Helfima** [comment]
implemented
Version: 0.12.20
Date: 2024-01-24
  Features:
    - Now we can use few beacons
    - Now we can add global effects on production line
