### ISSUE TITLE
Calculation of rocket fuel production

### ISSUE THREAD

**Issue by iceman121212** [Helfima/helmod#37]
Repost from https://forums.factorio.com/viewtopic.php?f=92&t=30465&start=20
***
This is a very useful mod! I wish I'd found it before I'd gone to the trouble of putting together my spreadsheet. 

I was hoping you might be able to help guide re: correct settings for rocket fuel production. For example, let's say we want the breakdown of ingredients necessary to generate 1 rocket fuel per second, assuming advanced cracking (and no modules or beacons to keep it simple).

We know that 1 rocket fuel requires 10 solid fuel, which we can make from ~11.21 (liters of) crude. Here are the calcs.

1. Advanced processing of 11.21 crude gives 1.12 heavy, 5.05 light and 6.17 petroleum. 
2. Cracking of 1.12 heavy gives 0.84 light, which we can combine with the 5.05 light from advanced processing to get a total of 5.89 light. 
3. Solid fuel conversion of 5.89 light gives 5.89 solid fuel, and solid fuel conversion of 6.17 petroleum gives 4.11 solid fuel, for a total of 10 solid fuel.

I'm unable to replicate this calculation in Helmod (image below)

The numbers in the blue circle are calculated from the figures above: heavy cracking gives ~14% of all light (0.84 / 5.89), solid fuel conversion of light gives ~59% of all solid fuel (5.89 / 10) and solid fuel conversion of petroleum gives 41% of all solid fuel (4.11 / 10).

What am I doing wrong?

![untitled](https://cloud.githubusercontent.com/assets/9387729/24430021/db528d12-13d1-11e7-9430-7550e9d67b5e.png)

**Comment by Helfima** [comment]
Hello
It is complicated to balance the productions but I have a method of approach.
Step 0:
Place all recipes.
We note that the second line produces all the blocks of fuels and we do not consume the other petroleum products.
![step0](https://cloud.githubusercontent.com/assets/20326713/24452870/b1e11b92-1485-11e7-90b1-dc6d21d4d241.png)
Step 1:
The production of the second line is minimized in order to have almost no surplus of the light petrol
![step1](https://cloud.githubusercontent.com/assets/20326713/24453132/ebbd4d3a-1486-11e7-9dde-cbd3c033e8c1.png)
Step 2:
We do not touch line 3 because we want to produce 100% of the blocks of fuels
Line 4 production is maximized to have almost no heavy p
![step2](https://cloud.githubusercontent.com/assets/20326713/24453350/bfb808c8-1487-11e7-8e16-dc8362569988.png)
etrol surplus
Step 3:
Lines 2 and 4 are adjusted to minimize surplus
![step3](https://cloud.githubusercontent.com/assets/20326713/24453435/1f0a8fbc-1488-11e7-959d-82f768368881.png)

**Comment by iceman121212** [comment]
Very helpful, tyvm!
