### ISSUE TITLE
Number of power machines

### ISSUE THREAD

**Issue by KiwiHawk** [Helfima/helmod#426]
### Energy machines
Number of power machines isn't changing when adjusting the Base time.

92.6 fluid burning heat sources is correct for Base time of 1s but wrong for base time of 1m.
![image](https://user-images.githubusercontent.com/59639/187657699-7205cfe4-ed65-41c3-be69-133b836977e1.png)

### Units
Units for electricity and heat should be in joules, not watts. Else it's wrong when using base time of anything other than 1s.

**Comment by EdwardMcCants** [comment]
On a possibly related note, 
The only difference between these two images is changing the Base time from 1s to 1min.
![image](https://user-images.githubusercontent.com/27255145/192912457-88824e6b-63da-47a6-80e8-bf9a42f9287c.png)
![image](https://user-images.githubusercontent.com/27255145/192912491-43890838-bfb7-4463-98b0-8a3e37c9212c.png)
In the production line information, the power consumed is shown as 5.5 MW for both base times.  However, the output electricity changes between the two.

I partially agree with the original poster; if you want it the electricity value to change with base time, it should be expressed as/in Joules (J) instead of Watts, otherwise the value should be expressed as/in Watts and not change with base time.
