### ISSUE TITLE
Space Exploration 1.1.61

### ISSUE THREAD

**Issue by P3t3r912** [Helfima/helmod#433]
cannot add helmod to existing save running Factorio 1.1.61
[test.zip](https://github.com/Helfima/helmod/files/9806252/test.zip)
[message.txt](https://github.com/Helfima/helmod/files/9806255/message.txt)
![image](https://user-images.githubusercontent.com/116045046/196329940-5f748f98-084c-49aa-ab29-4651a57fd7da.png)

**Comment by KiwiHawk** [comment]
I've not been able to reproduce the issue with your new save unfortunately. My steps:
- Sync game to provided save test.zip
- Enable Helmod
- Load test.zip

Are you able to reproduce the issue by following these steps? If not, I might have to ask you to upload the save to dropbox or something like that.

I don't actually think the error is caused by a bug in Helmod. But I'd like to make sure, if possible. And also help you out. Relevant line from the log:
```
Stack trace logging done
  39.441 Error Map.cpp:2077: Active entities count doesn't match. Current: 1262525, expected 1262526.
```

One thing you could try is upgrade to the latest version of Factorio (1.1.70). It's possible that this may already have been fixed

**Comment by P3t3r912** [comment]
[factorio-current.log](https://github.com/Helfima/helmod/files/9811748/factorio-current.log)
updated to current Factorio 1.1.70 and get same crash
