### ISSUE TITLE
Minimum speed from productivity modules

### ISSUE THREAD

**Issue by TokMor** [Helfima/helmod#69]
Putting high tier productivity modules in a machine does not respect the in game limit to speed penalty. It also can cause helmod to calculate a negative number of machines as a result. See the attached as an example. If more information is required please let me know.

http://imgur.com/a/0jy4p

**Comment by Helfima** [comment]
ohoh I must check this situation

**Comment by Helfima** [comment]
i can't try because i can't load angelsmelting
error with bob dependencie
![bobangel1](https://cloud.githubusercontent.com/assets/20326713/26600990/77eb0ffe-457e-11e7-9ad0-432e70ffb077.PNG)
![bobangel2](https://cloud.githubusercontent.com/assets/20326713/26600989/77e87a32-457e-11e7-960a-92457b0615d0.PNG)

**Comment by Helfima** [comment]
you can try version 0.5.4
